name: Run qBittorrent Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lbry-libtorrent python-telegram-bot speedtest-cli requests requests-toolbelt aiohttp

    - name: Run Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GOFILE_API_KEY: ${{ secrets.GOFILE_API_KEY }}
      run: |
        mkdir ./downloads/
        python torrent.py
