name: Run qBittorrent Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install qbittorrent-api python-telegram-bot speedtest-cli

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Criar rclone.conf a partir de segredos
      run: |
        mkdir -p ~/.config/rclone/
        echo "[gofile]" > ~/.config/rclone/rclone.conf
        echo "type = gofile" >> ~/.config/rclone/rclone.conf
        echo "api_key = ${{ secrets.RCLONE_GOFILE_API_KEY }}" >> ~/.config/rclone/rclone.conf

    - name: Mount rclone
      run: |
        sudo mkdir -p /mnt/rclone/Torrent/
        sudo rclone mount gofile: /mnt/rclone/Torrent/ --vfs-cache-mode full &

    - name: Run Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GOFILE_API_KEY: ${{ secrets.GOFILE_API_KEY }}
      run: |
        python gofilebot.py
